# Agent: Researcher - High-level research and synthesis tools.
# Cobalt Multiagent - Research Module

# Copyright (c) 2026 Dave Wilkinson <dwilkins@bluesec.ai>
# License: PolyForm Noncommercial 1.0.0

import logging
from typing import List, Dict, Any
from langchain_core.tools import tool
from .finance import get_symbol_history_data


from .shared_storage import RESEARCHER_CONTEXT, GLOBAL_CONTEXT

logger = logging.getLogger(__name__)

# 1. Private context: Truly private to this module instance (Durable durante the node execution).
_NODE_RESOURCE_CONTEXT: Dict[str, Any] = {}

# 2. Shared context: Persistent, shared by all agents of the SAME type.
_SHARED_RESOURCE_CONTEXT = RESEARCHER_CONTEXT

# 3. Global context: Persistent, shared by ALL agents of ANY type.
_GLOBAL_RESOURCE_CONTEXT = GLOBAL_CONTEXT


# Module Rules: Define the standard macro set and retrieval constraints
RULES = {
    "MACRO_SET": ["DX-Y.NYB", "^TNX", "SPY", "QQQ", "IWM", "^VIX", "GLD", "BTC-USD", "USO"],
    "DEFAULT_LOOKBACK": "1d",
    "DEFAULT_INTERVAL": "1h"
}

@tool
async def fetch_market_macros() -> str:
    """
    Fetch comprehensive market macro data for key global indices and assets.
    Included assets: Dollar Index (DXY), 10Y Yield (TNX), S&P 500 (SPY), Nasdaq (QQQ), 
    Russell 2000 (IWM), Volatility (VIX), Gold (GLD), Bitcoin (BTC), and Oil (USO).
    
    This tool delegates retrieval to the Scout's get_stock_list_history primitive 
    using the research module's predefined rules.
    """
    logger.info("Research Module: Initiating global macro fetch via Scout primitive")
    
    symbols = RULES["MACRO_SET"]
    lookback = RULES["DEFAULT_LOOKBACK"]
    interval = RULES["DEFAULT_INTERVAL"]
    
    # Internal delegation to the Scout primitive
    try:
        # Note: In a real multi-agent flow, the agent would call this tool.
        # Here we invoke the tool directly as a library function for the composite tool.
        report = await get_symbol_history_data.ainvoke({
            "symbols": symbols,
            "period": lookback,
            "interval": interval
        })

        
        return f"""
# 🌐 Global Market Macro Report
Generated by: Research Module (VIBE v2)
Ruleset: Standard Global Macro

{report}

---
*Note: This report is a synthesis of raw data retrieved by the Scout.*
""".strip()

    except Exception as e:
        logger.error(f"Research Module Error: {str(e)}")
        return f"[ERROR]: Research module failed to fetch macros: {str(e)}"
